{
KEY_CODE_YES = 0x100,  -- If get_wch() gives a key code 

KEY_BREAK = 0x101,  -- Not on PC KBD 
KEY_DOWN = 0x102,  -- Down arrow key 
KEY_UP = 0x103,  -- Up arrow key 
KEY_LEFT = 0x104,  -- Left arrow key 
KEY_RIGHT = 0x105,  -- Right arrow key 
KEY_HOME = 0x106,  -- home key 
KEY_BACKSPACE = 0x107,  -- not on pc 
KEY_F0 = 0x108,  -- function keys; 64 reserved 

KEY_DL = 0x148,  -- delete line 
KEY_IL = 0x149,  -- insert line 
KEY_DC = 0x14a,  -- delete character 
KEY_IC = 0x14b,  -- insert char or enter ins mode 
KEY_EIC = 0x14c,  -- exit insert char mode 
KEY_CLEAR = 0x14d,  -- clear screen 
KEY_EOS = 0x14e,  -- clear to end of screen 
KEY_EOL = 0x14f,  -- clear to end of line 
KEY_SF = 0x150,  -- scroll 1 line forward 
KEY_SR = 0x151,  -- scroll 1 line back (reverse) 
KEY_NPAGE = 0x152,  -- next page 
KEY_PPAGE = 0x153,  -- previous page 
KEY_STAB = 0x154,  -- set tab 
KEY_CTAB = 0x155,  -- clear tab 
KEY_CATAB = 0x156,  -- clear all tabs 
KEY_ENTER = 0x157,  -- enter or send (unreliable) 
KEY_SRESET = 0x158,  -- soft/reset (partial/unreliable) 
KEY_RESET = 0x159,  -- reset/hard reset (unreliable) 
KEY_PRINT = 0x15a,  -- print/copy 
KEY_LL = 0x15b,  -- home down/bottom (lower left) 
KEY_ABORT = 0x15c,  -- abort/terminate key (any) 
KEY_SHELP = 0x15d,  -- short help 
KEY_LHELP = 0x15e,  -- long help 
KEY_BTAB = 0x15f,  -- Back tab key 
KEY_BEG = 0x160,  -- beg(inning) key 
KEY_CANCEL = 0x161,  -- cancel key 
KEY_CLOSE = 0x162,  -- close key 
KEY_COMMAND = 0x163,  -- cmd (command) key 
KEY_COPY = 0x164,  -- copy key 
KEY_CREATE = 0x165,  -- create key 
KEY_END = 0x166,  -- end key 
KEY_EXIT = 0x167,  -- exit key 
KEY_FIND = 0x168,  -- find key 
KEY_HELP = 0x169,  -- help key 
KEY_MARK = 0x16a,  -- mark key 
KEY_MESSAGE = 0x16b,  -- message key 
KEY_MOVE = 0x16c,  -- move key 
KEY_NEXT = 0x16d,  -- next object key 
KEY_OPEN = 0x16e,  -- open key 
KEY_OPTIONS = 0x16f,  -- options key 
KEY_PREVIOUS = 0x170,  -- previous object key 
KEY_REDO = 0x171,  -- redo key 
KEY_REFERENCE = 0x172,  -- ref(erence) key 
KEY_REFRESH = 0x173,  -- refresh key 
KEY_REPLACE = 0x174,  -- replace key 
KEY_RESTART = 0x175,  -- restart key 
KEY_RESUME = 0x176,  -- resume key 
KEY_SAVE = 0x177,  -- save key 
KEY_SBEG = 0x178,  -- shifted beginning key 
KEY_SCANCEL = 0x179,  -- shifted cancel key 
KEY_SCOMMAND = 0x17a,  -- shifted command key 
KEY_SCOPY = 0x17b,  -- shifted copy key 
KEY_SCREATE = 0x17c,  -- shifted create key 
KEY_SDC = 0x17d,  -- shifted delete char key 
KEY_SDL = 0x17e,  -- shifted delete line key 
KEY_SELECT = 0x17f,  -- select key 
KEY_SEND = 0x180,  -- shifted end key 
KEY_SEOL = 0x181,  -- shifted clear line key 
KEY_SEXIT = 0x182,  -- shifted exit key 
KEY_SFIND = 0x183,  -- shifted find key 
KEY_SHOME = 0x184,  -- shifted home key 
KEY_SIC = 0x185,  -- shifted input key 

KEY_SLEFT = 0x187,  -- shifted left arrow key 
KEY_SMESSAGE = 0x188,  -- shifted message key 
KEY_SMOVE = 0x189,  -- shifted move key 
KEY_SNEXT = 0x18a,  -- shifted next key 
KEY_SOPTIONS = 0x18b,  -- shifted options key 
KEY_SPREVIOUS = 0x18c,  -- shifted prev key 
KEY_SPRINT = 0x18d,  -- shifted print key 
KEY_SREDO = 0x18e,  -- shifted redo key 
KEY_SREPLACE = 0x18f,  -- shifted replace key 
KEY_SRIGHT = 0x190,  -- shifted right arrow 
KEY_SRSUME = 0x191,  -- shifted resume key 
KEY_SSAVE = 0x192,  -- shifted save key 
KEY_SSUSPEND = 0x193,  -- shifted suspend key 
KEY_SUNDO = 0x194,  -- shifted undo key 
KEY_SUSPEND = 0x195,  -- suspend key 
KEY_UNDO = 0x196,  -- undo key 

-- PDCurses-specific key definitions -- PC only 

ALT_0 = 0x197,
ALT_1 = 0x198,
ALT_2 = 0x199,
ALT_3 = 0x19a,
ALT_4 = 0x19b,
ALT_5 = 0x19c,
ALT_6 = 0x19d,
ALT_7 = 0x19e,
ALT_8 = 0x19f,
ALT_9 = 0x1a0,
ALT_A = 0x1a1,
ALT_B = 0x1a2,
ALT_C = 0x1a3,
ALT_D = 0x1a4,
ALT_E = 0x1a5,
ALT_F = 0x1a6,
ALT_G = 0x1a7,
ALT_H = 0x1a8,
ALT_I = 0x1a9,
ALT_J = 0x1aa,
ALT_K = 0x1ab,
ALT_L = 0x1ac,
ALT_M = 0x1ad,
ALT_N = 0x1ae,
ALT_O = 0x1af,
ALT_P = 0x1b0,
ALT_Q = 0x1b1,
ALT_R = 0x1b2,
ALT_S = 0x1b3,
ALT_T = 0x1b4,
ALT_U = 0x1b5,
ALT_V = 0x1b6,
ALT_W = 0x1b7,
ALT_X = 0x1b8,
ALT_Y = 0x1b9,
ALT_Z = 0x1ba,

CTL_LEFT = 0x1bb,  -- Control-Left-Arrow 
CTL_RIGHT = 0x1bc,
CTL_PGUP = 0x1bd,
CTL_PGDN = 0x1be,
CTL_HOME = 0x1bf,
CTL_END = 0x1c0,

KEY_A1 = 0x1c1,  -- upper left on Virtual keypad 
KEY_A2 = 0x1c2,  -- upper middle on Virt. keypad 
KEY_A3 = 0x1c3,  -- upper right on Vir. keypad 
KEY_B1 = 0x1c4,  -- middle left on Virt. keypad 
KEY_B2 = 0x1c5,  -- center on Virt. keypad 
KEY_B3 = 0x1c6,  -- middle right on Vir. keypad 
KEY_C1 = 0x1c7,  -- lower left on Virt. keypad 
KEY_C2 = 0x1c8,  -- lower middle on Virt. keypad 
KEY_C3 = 0x1c9,  -- lower right on Vir. keypad 

PADSLASH = 0x1ca,  -- slash on keypad 
PADENTER = 0x1cb,  -- enter on keypad 
CTL_PADENTER = 0x1cc,  -- ctl-enter on keypad 
ALT_PADENTER = 0x1cd,  -- alt-enter on keypad 
PADSTOP = 0x1ce,  -- stop on keypad 
PADSTAR = 0x1cf,  -- star on keypad 
PADMINUS = 0x1d0,  -- minus on keypad 
PADPLUS = 0x1d1,  -- plus on keypad 
CTL_PADSTOP = 0x1d2,  -- ctl-stop on keypad 
CTL_PADCENTER = 0x1d3,  -- ctl-enter on keypad 
CTL_PADPLUS = 0x1d4,  -- ctl-plus on keypad 
CTL_PADMINUS = 0x1d5,  -- ctl-minus on keypad 
CTL_PADSLASH = 0x1d6,  -- ctl-slash on keypad 
CTL_PADSTAR = 0x1d7,  -- ctl-star on keypad 
ALT_PADPLUS = 0x1d8,  -- alt-plus on keypad 
ALT_PADMINUS = 0x1d9,  -- alt-minus on keypad 
ALT_PADSLASH = 0x1da,  -- alt-slash on keypad 
ALT_PADSTAR = 0x1db,  -- alt-star on keypad 
ALT_PADSTOP = 0x1dc,  -- alt-stop on keypad 
CTL_INS = 0x1dd,  -- ctl-insert 
ALT_DEL = 0x1de,  -- alt-delete 
ALT_INS = 0x1df,  -- alt-insert 
CTL_UP = 0x1e0,  -- ctl-up arrow 
CTL_DOWN = 0x1e1,  -- ctl-down arrow 
CTL_TAB = 0x1e2,  -- ctl-tab 
ALT_TAB = 0x1e3,
ALT_MINUS = 0x1e4,
ALT_EQUAL = 0x1e5,
ALT_HOME = 0x1e6,
ALT_PGUP = 0x1e7,
ALT_PGDN = 0x1e8,
ALT_END = 0x1e9,
ALT_UP = 0x1ea,  -- alt-up arrow 
ALT_DOWN = 0x1eb,  -- alt-down arrow 
ALT_RIGHT = 0x1ec,  -- alt-right arrow 
ALT_LEFT = 0x1ed,  -- alt-left arrow 
ALT_ENTER = 0x1ee,  -- alt-enter 
ALT_ESC = 0x1ef,  -- alt-escape 
ALT_BQUOTE = 0x1f0,  -- alt-back quote 
ALT_LBRACKET = 0x1f1,  -- alt-left bracket 
ALT_RBRACKET = 0x1f2,  -- alt-right bracket 
ALT_SEMICOLON = 0x1f3,  -- alt-semi-colon 
ALT_FQUOTE = 0x1f4,  -- alt-forward quote 
ALT_COMMA = 0x1f5,  -- alt-comma 
ALT_STOP = 0x1f6,  -- alt-stop 
ALT_FSLASH = 0x1f7,  -- alt-forward slash 
ALT_BKSP = 0x1f8,  -- alt-backspace 
CTL_BKSP = 0x1f9,  -- ctl-backspace 
PAD0 = 0x1fa,  -- keypad 0 

CTL_PAD0 = 0x1fb,  -- ctl-keypad 0 
CTL_PAD1 = 0x1fc,
CTL_PAD2 = 0x1fd,
CTL_PAD3 = 0x1fe,
CTL_PAD4 = 0x1ff,
CTL_PAD5 = 0x200,
CTL_PAD6 = 0x201,
CTL_PAD7 = 0x202,
CTL_PAD8 = 0x203,
CTL_PAD9 = 0x204,

ALT_PAD0 = 0x205,  -- alt-keypad 0 
ALT_PAD1 = 0x206,
ALT_PAD2 = 0x207,
ALT_PAD3 = 0x208,
ALT_PAD4 = 0x209,
ALT_PAD5 = 0x20a,
ALT_PAD6 = 0x20b,
ALT_PAD7 = 0x20c,
ALT_PAD8 = 0x20d,
ALT_PAD9 = 0x20e,

CTL_DEL = 0x20f,  -- clt-delete 
ALT_BSLASH = 0x210,  -- alt-back slash 
CTL_ENTER = 0x211,  -- ctl-enter 

SHF_PADENTER = 0x212,  -- shift-enter on keypad 
SHF_PADSLASH = 0x213,  -- shift-slash on keypad 
SHF_PADSTAR = 0x214,  -- shift-star  on keypad 
SHF_PADPLUS = 0x215,  -- shift-plus  on keypad 
SHF_PADMINUS = 0x216,  -- shift-minus on keypad 
SHF_UP = 0x217,  -- shift-up on keypad 
SHF_DOWN = 0x218,  -- shift-down on keypad 
SHF_IC = 0x219,  -- shift-insert on keypad 
SHF_DC = 0x21a,  -- shift-delete on keypad 

KEY_MOUSE = 0x21b,  -- "mouse" key 
KEY_SHIFT_L = 0x21c,  -- Left-shift 
KEY_SHIFT_R = 0x21d,  -- Right-shift 
KEY_CONTROL_L = 0x21e,  -- Left-control 
KEY_CONTROL_R = 0x21f,  -- Right-control 
KEY_ALT_L = 0x220,  -- Left-alt 
KEY_ALT_R = 0x221,  -- Right-alt 
KEY_RESIZE = 0x222,  -- Window resize 
KEY_SUP = 0x223,  -- Shifted up arrow 
KEY_SDOWN = 0x224,  -- Shifted down arrow 

KEY_MIN = KEY_BREAK,      -- Minimum curses key value 
KEY_MAX = KEY_SDOWN,      -- Maximum curses key 

}